### PR TITLE
Remove boost python lib suffix

### PR DESCRIPTION
**Pull request by oktomus**
The naming of boost libraries is the following:
- libboost_python for python 2
- libboost_python3x for python 3.x

### CODE REVIEW

**Comment by Achimh3011** [comment]
On which distributions?

**Comment by oktomus** [comment]
Archlinux. Is it supposed to be different on all distributions ?

**Comment by Achimh3011** [comment]
Unfortunately yes.

But it's good to have more distros tested. i only checked openSUSE and Ubuntu so far.

**Comment by oktomus** [comment]
I'll see if we can do something generic.

**Comment by FluorineDog** [comment]
Using boost 1.65, change _build.sh_ to -DPYTHON_VERSION_SUFFIX=**3** insead of **-py3**
Tested on Ubuntu 18.04

**Comment by oktomus** [comment]
So should we close this PR and forget about it ?

**Comment by Achimh3011** [comment]
Either that or modify it such that it will allow building on more systems out-of-the-box.

**Pull request closed without merging**
