### PR TITLE
Boost python recognition

### PR DESCRIPTION
**Pull request by Achimh3011**

### CODE REVIEW

**Comment by Achimh3011** [comment]
@dendisuhubdy Does this PR still work for you?

**Comment by dendisuhubdy** [comment]
@Achimh3011 checking

**Comment by dendisuhubdy** [comment]
``` grokmachine@spock  ~/dev/boost-python-examples/build  ➦ 38d824f  cmake ..
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.15")
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   python27
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.10")
-- PYTHON_LIBRARIES = /usr/lib/libpython2.7.dylib
-- PYTHON_EXECUTABLE = /usr/local/bin/python
-- PYTHON_INCLUDE_DIRS = /usr/include/python2.7
-- Boost_LIBRARIES = /usr/local/lib/libboost_python27-mt.dylib
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/grokmachine/dev/boost-python-examples/build
 grokmachine@spock  ~/dev/boost-python-examples/build  ➦ 38d824f  make -j16
Scanning dependencies of target virtual
Scanning dependencies of target policies
Scanning dependencies of target classes
Scanning dependencies of target inheritance
Scanning dependencies of target hello
Scanning dependencies of target operators
Scanning dependencies of target ctor
Scanning dependencies of target member
Scanning dependencies of target overload
Scanning dependencies of target mymodule
Scanning dependencies of target embedding
Scanning dependencies of target myexceptions
Scanning dependencies of target auto_instance
Scanning dependencies of target iterators
[  3%] Building CXX object 08-CallPolicies/CMakeFiles/policies.dir/policies.cpp.o
[  6%] Building CXX object 06-VirtualFunctionsInPython/CMakeFiles/virtual.dir/virtual.cpp.o
[ 10%] Building CXX object 09-Overloading/CMakeFiles/overload.dir/overload.cpp.o
[ 13%] Building CXX object 01-HelloWorld/CMakeFiles/hello.dir/hello.cpp.o
[ 16%] Building CXX object 11-Iterators/CMakeFiles/iterators.dir/iterators.cpp.o
[ 20%] Building CXX object 02-ExposingClasses/CMakeFiles/classes.dir/classes.cpp.o
[ 23%] Building CXX object 05-Inheritance/CMakeFiles/inheritance.dir/inheritance.cpp.o
[ 26%] Building CXX object 07-Operators/CMakeFiles/operators.dir/operators.cpp.o
[ 30%] Building CXX object 10-Embedding/CMakeFiles/mymodule.dir/mymodule.cpp.o
[ 33%] Building CXX object 03-Constructors/CMakeFiles/ctor.dir/ctor.cpp.o
[ 36%] Building CXX object 12-Exceptions/CMakeFiles/myexceptions.dir/myexceptions.cpp.o
[ 40%] Building CXX object 04-ClassMembers/CMakeFiles/member.dir/member.cpp.o
[ 43%] Building CXX object 10-Embedding/CMakeFiles/embedding.dir/mymodule.cpp.o
[ 46%] Building CXX object 10-Embedding/CMakeFiles/embedding.dir/embedding.cpp.o
[ 50%] Building CXX object 13-AutoInstantiation/CMakeFiles/auto_instance.dir/myextension.cpp.o
[ 53%] Building CXX object 13-AutoInstantiation/CMakeFiles/auto_instance.dir/auto_instance.cpp.o
[ 56%] Linking CXX shared module hello.so
[ 56%] Built target hello
[ 60%] Linking CXX shared module myexceptions.so
[ 63%] Linking CXX shared module policies.so
[ 66%] Linking CXX shared module mymodule.so
[ 66%] Built target myexceptions
[ 66%] Built target policies
[ 70%] Linking CXX shared module virtual.so
[ 70%] Built target mymodule
[ 73%] Linking CXX executable auto_instance
[ 76%] Linking CXX executable embedding
[ 76%] Built target virtual
[ 80%] Linking CXX shared module classes.so
[ 83%] Linking CXX shared module member.so
[ 86%] Linking CXX shared module ctor.so
[ 86%] Built target auto_instance
[ 86%] Built target embedding
[ 90%] Linking CXX shared module operators.so
[ 90%] Built target classes
[ 93%] Linking CXX shared module inheritance.so
[ 93%] Built target member
[ 93%] Built target ctor
[ 96%] Linking CXX shared module iterators.so
[ 96%] Built target operators
[100%] Linking CXX shared module overload.so
[100%] Built target inheritance
[100%] Built target iterators
[100%] Built target overload``` working so far for python2.7

**Comment by Achimh3011** [comment]
Actually not: interpreter and libs are not in sync. Compilation works, but tests will fail (see #17). However, using `./build.sh` should fix this.

**Pull request merged**
